/*

//HEALING

IF
Global("L0HealingExtra","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("L0HealingExtra","GLOBAL",1)
AddSpecialAbility("L0SPIHEA")
END

*/

IF
InParty(Myself)
Global("L0WillJoin25","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("L0WillJoin25","GLOBAL",1)
END


IF
Global("L0willSummonedToB","GLOBAL",1)
Global("L0StartWithMeToB","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("L0StartWithMeToB","GLOBAL",1)
StartDialogueNoSet(Player1)
END

IF
!AreaCheck("AR4000")
PartyHasItem("l0willne")
HPLT(Myself,2)
THEN
RESPONSE #100
CreateVisualEffectObject("SPCLOUD1",Myself)
DropInventory()
SetLeavePartyDialogueFile()
LeaveParty()
SetGlobal("L0WillJoin25","GLOBAL",0)
ForceSpellRES("L0heal",Myself)
ChangeAIScript("",DEFAULT)
DisplayStringHead(Player1,@19000)
MoveGlobal("AR4500","L0Will",[2242.1130])
END

/////////////////////////////////////////
/////////////////////////////////////////

IF
AreaCheck("AR4000")
Global("L0WillJoin25","GLOBAL",0)
THEN
RESPONSE #100
StartDialogue("L0Wil25J",Player1)
END

/////////////////////////////////////////
/////////////////////////////////////////

IF
InParty(Myself)
Global("L0WillJoin25","GLOBAL",1)
Global("L0WillUsualToB","GLOBAL",0)
THEN
RESPONSE #100
RealSetGlobalTimer("L0WillUsualToBTime","GLOBAL",600)
SetGlobal("L0WillUsualToB","GLOBAL",1)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
Global("L0WillUsualToB","GLOBAL",1)
RealGlobalTimerExpired("L0WillUsualToBTime","GLOBAL")
THEN
RESPONSE #100
SetGlobal("L0WillUsualToB","GLOBAL",2)
END

IF
Global("L0WillUsualToB","GLOBAL",2)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogue("L0Wil25J",Player1)
END

IF
InParty(Myself)
Global("L0WillUsualToB","GLOBAL",3)
RealGlobalTimerExpired("L0WillUsualToBTime","GLOBAL")
THEN
RESPONSE #100
RealSetGlobalTimer("L0WillUsualToBTime","GLOBAL",1800)
SetGlobal("L0WillUsualToB","GLOBAL",4)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
Global("L0WillUsualToB","GLOBAL",4)
RealGlobalTimerExpired("L0WillUsualToBTime","GLOBAL")
THEN
RESPONSE #100
SetGlobal("L0WillUsualToB","GLOBAL",5)
END

IF
Global("L0WillUsualToB","GLOBAL",5)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogue("L0Wil25J",Player1)
END

IF
InParty(Myself)
Global("L0WillUsualToB","GLOBAL",6)
RealGlobalTimerExpired("L0WillUsualToBTime","GLOBAL")
THEN
RESPONSE #100
RealSetGlobalTimer("L0WillUsualToBTime","GLOBAL",1800)
SetGlobal("L0WillUsualToB","GLOBAL",7)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
Global("L0WillUsualToB","GLOBAL",7)
RealGlobalTimerExpired("L0WillUsualToBTime","GLOBAL")
THEN
RESPONSE #100
SetGlobal("L0WillUsualToB","GLOBAL",8)
END

IF
Global("L0WillUsualToB","GLOBAL",8)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogue("L0Wil25J",Player1)
END

IF
InParty(Myself)
Global("L0WillRelationshipActive","GLOBAL",2)
RealGlobalTimerExpired("L0WillUsualToBTime","GLOBAL")
Global("L0WillUsualToB","GLOBAL",9)
Global("L0WillBrotherhoodToB","GLOBAL",0)
THEN
RESPONSE #100
RealSetGlobalTimer("L0WillUsualToBTime","GLOBAL",1800)
SetGlobal("L0WillBrotherhoodToB","GLOBAL",1)
SetGlobal("L0WillUsualToB","GLOBAL",10)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
Global("L0WillBrotherhoodToB","GLOBAL",1)
Global("L0WillRelationshipActive","GLOBAL",2)
RealGlobalTimerExpired("L0WillUsualToBTime","GLOBAL")
THEN
RESPONSE #100
SetGlobal("L0WillBrotherhoodToB","GLOBAL",2)
END

IF
Global("L0WillBrotherhoodToB","GLOBAL",2)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogue("L0Wil25J",Player1)
END

IF
InParty(Myself)
Global("L0WillRelationshipActive","GLOBAL",2)
Global("L0WillBrotherhoodToB","GLOBAL",3)
RealGlobalTimerExpired("L0WillUsualToBTime","GLOBAL")
THEN
RESPONSE #100
RealSetGlobalTimer("L0WillUsualToBTime","GLOBAL",1800)
SetGlobal("L0WillBrotherhoodToB","GLOBAL",4)
END

IF
Global("L0WillBrotherhoodToB","GLOBAL",4)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogue("L0Wil25J",Player1)
END


IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
Global("L0WillRelationshipActive","GLOBAL",2)
Global("L0WillBrotherhoodToB","GLOBAL",5)
GlobalGT("BeginChallenge5","GLOBAL",3)
THEN
RESPONSE #100
SetGlobal("L0WillBrotherhoodToB","GLOBAL",6)
END

IF
Global("L0WillBrotherhoodToB","GLOBAL",6)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogue("L0Wil25J",Player1)
END


/////////////////////////////////////////
/////////////////////////////////////////


IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
Global("SaradushSacked","GLOBAL",1)
Global("L0SaradushWill","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("L0SaradushWill","GLOBAL",1)
END

IF
Global("L0SaradushWill","GLOBAL",1)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogue("L0Wil25J",Player1)
END