/*

//HEALING

IF
Global("L0HealingExtra","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("L0HealingExtra","GLOBAL",1)
AddSpecialAbility("L0SPIHEA")
END

*/

//DEATH

IF
PartyHasItem("l0willn0")
!AreaCheck("L00000")
!AreaCheck("AR1400")
!AreaCheck("AR1401")
!AreaCheck("AR1402")
!AreaCheck("AR1403")
!AreaCheck("AR1404")
THEN
RESPONSE #100
SetGlobal("L0WillJoin","GLOBAL",0)
LeaveParty()
Kill("L0Will")
END

IF
PartyHasItem("l0willne")
HPLT(Myself,2)
THEN
RESPONSE #100
CreateVisualEffectObject("SPCLOUD1",Myself)
DropInventory()
SetLeavePartyDialogueFile()
LeaveParty()
SetGlobal("L0WillJoin","GLOBAL",0)
IncrementGlobal("L0WillDead","GLOBAL",1)
ForceSpellRES("L0heal",Myself)
ChangeAIScript("",DEFAULT)
DisplayStringHead(Player1,@18000)
MoveGlobal("AR1400","L0Will",[2032.120])
END

//DIALOGUE - GRAVE

IF
See("L0SQ")
Global("L0WillDeath","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("L0WillDeath","GLOBAL",1)
END

IF
Global("L0WillDeath","GLOBAL",1)
THEN
RESPONSE #100
StartDialogue("L0WILLJ",Player1)
END

IF
Global("L0WillDeath","GLOBAL",2)
THEN
RESPONSE #100
StartCutScene("L0CUT03")
END

IF
Global("L0WillDeath","GLOBAL",3)
THEN
RESPONSE #100
StartDialogue("L0WILLJ",Player1)
END

//DIALOGUE - CITY

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
Global("L0WillDialogue","GLOBAL",0)
OR(9)
AreaCheck("AR0020")
AreaCheck("AR0300")
AreaCheck("AR0400")
AreaCheck("AR0500")
AreaCheck("AR0700")
AreaCheck("AR0900")
AreaCheck("AR1000")
AreaCheck("YS0390")
AreaCheck("AR2000")
THEN
RESPONSE #100
SetGlobal("L0WillDialogue","GLOBAL",1)
END

IF
Global("L0WillDialogue","GLOBAL",1)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogue("L0WillJ",Player1)
END

IF
Global("L0WillDialogue","GLOBAL",2)
THEN
RESPONSE #100
RealSetGlobalTimer("L0WillTimer","GLOBAL",2400)
SetGlobal("L0WillDialogue","GLOBAL",3)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
Global("L0WillDialogue","GLOBAL",3)
RealGlobalTimerExpired("L0WillTimer","GLOBAL")
THEN
RESPONSE #100
SetGlobal("L0WillDialogue","GLOBAL",4)
END

IF
Global("L0WillDialogue","GLOBAL",4)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogue("L0WillJ",Player1)
END

IF
Global("L0WillDialogue","GLOBAL",5)
THEN
RESPONSE #100
RealSetGlobalTimer("L0WillTimer","GLOBAL",2400)
SetGlobal("L0WillDialogue","GLOBAL",6)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
Global("L0WillDialogue","GLOBAL",6)
RealGlobalTimerExpired("L0WillTimer","GLOBAL")
THEN
RESPONSE #100
SetGlobal("L0WillDialogue","GLOBAL",7)
END

IF
Global("L0WillDialogue","GLOBAL",7)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogue("L0WillJ",Player1)
END

IF
Global("L0WillDialogue","GLOBAL",8)
THEN
RESPONSE #100
RealSetGlobalTimer("L0WillTimer","GLOBAL",2400)
SetGlobal("L0WillDialogue","GLOBAL",9)
END

IF
Global("L0WillDialogue","GLOBAL",10)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogue("L0WillJ",Player1)
END

IF
Global("L0WillDialogue","GLOBAL",11)
THEN
RESPONSE #100
RealSetGlobalTimer("L0WillTimer","GLOBAL",2400)
SetGlobal("L0WillDialogue","GLOBAL",12)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
Global("L0WillDialogue","GLOBAL",12)
RealGlobalTimerExpired("L0WillTimer","GLOBAL")
THEN
RESPONSE #100
SetGlobal("L0WillDialogue","GLOBAL",13)
END

IF
Global("L0WillDialogue","GLOBAL",13)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogue("L0WillJ",Player1)
END

IF
Global("L0WillDialogue","GLOBAL",14)
THEN
RESPONSE #100
RealSetGlobalTimer("L0WillTimer","GLOBAL",2400)
SetGlobal("L0WillDialogue","GLOBAL",15)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
Global("L0WillDialogue","GLOBAL",15)
RealGlobalTimerExpired("L0WillTimer","GLOBAL")
THEN
RESPONSE #100
SetGlobal("L0WillDialogue","GLOBAL",16)
END

IF
Global("L0WillDialogue","GLOBAL",16)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogue("L0WillJ",Player1)
END

IF
Global("L0WillDialogue","GLOBAL",17)
THEN
RESPONSE #100
RealSetGlobalTimer("L0WillTimer","GLOBAL",2400)
SetGlobal("L0WillDialogue","GLOBAL",18)
END

IF
Global("L0WillDialogue","GLOBAL",19)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogue("L0WillJ",Player1)
END

//FAMILY MATTERS

IF
Global("L0WillAndBoy","GLOBAL",1)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogue("L0WillJ",Player1)
END

//DIALOGUE - TOMB

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
Global("L0WillTomb","GLOBAL",0)
OR(3)
AreaCheck("AR0802")
AreaCheck("AR0803")
AreaCheck("AR0809")
THEN
RESPONSE #100
SetGlobal("L0WillTomb","GLOBAL",1)
END

IF
Global("L0WillTomb","GLOBAL",1)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogue("L0WillJ",Player1)
END

//DIALOGUE - CHANGE

IF
InParty(Myself)
See(Player1)
Global("L0WillRelationshipActive","GLOBAL",2)
Global("L0WillChange","GLOBAL",0)
AreaCheck("AR1507")
THEN
RESPONSE #100
SetGlobal("L0WillChange","GLOBAL",1)
END

IF
Global("L0WillChange","GLOBAL",1)
THEN
RESPONSE #100
StartDialogue("L0WillJ",Player1)
END

//DIALOGUE - DROW

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
Global("L0WillDrow","GLOBAL",0)
AreaCheck("AR2200")
THEN
RESPONSE #100
SetGlobal("L0WillDrow","GLOBAL",1)
RealSetGlobalTimer("L0WillTimerDrow","GLOBAL",30)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
AreaCheck("AR2200")
Global("L0WillDrow","GLOBAL",1)
RealGlobalTimerExpired("L0WillTimerDrow","GLOBAL")
THEN
RESPONSE #100
SetGlobal("L0WillDrow","GLOBAL",2)
END

IF
Global("L0WillDrow","GLOBAL",2)
THEN
RESPONSE #100
StartDialogue("L0WillJ",Player1)
END

//DIALOGUE - CHAPTER 6

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
Global("L0WillCH2","GLOBAL",0)
AreaCheck("AR2500")
THEN
RESPONSE #100
SetGlobal("L0WillCH2","GLOBAL",1)
RealSetGlobalTimer("L0WillTimerCH6","GLOBAL",90)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
Global("L0WillCH2","GLOBAL",1)
RealGlobalTimerExpired("L0WillTimerCH6","GLOBAL")
THEN
RESPONSE #100
SetGlobal("L0WillCH2","GLOBAL",2)
END

IF
Global("L0WillCH2","GLOBAL",2)
THEN
RESPONSE #100
StartDialogue("L0WillJ",Player1)
END

//DIALOGUE - ELVEN

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
Global("L0WillElven","GLOBAL",0)
AreaCheck("AR2800")
THEN
RESPONSE #100
SetGlobal("L0WillElven","GLOBAL",1)
RealSetGlobalTimer("L0WillTimerElven","GLOBAL",20)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
Global("L0WillElven","GLOBAL",1)
RealGlobalTimerExpired("L0WillTimerElven","GLOBAL")
THEN
RESPONSE #100
SetGlobal("L0WillElven","GLOBAL",2)
END

IF
Global("L0WillElven","GLOBAL",2)
THEN
RESPONSE #100
StartDialogue("L0WillJ",Player1)
END

////////////////////////
////PLAYER HAS ROMANCE//
////////////////////////

IF
Gender(Player1,FEMALE)
Global("L0Player1Gay","GLOBAL",0)
OR(11)
Global("JaheiraRomanceActive","GLOBAL",2)
Global("ViconiaRomanceActive","GLOBAL",2)
Global("AerieRomanceActive","GLOBAL",2)
Global("ChloeRomanceActiveCR","GLOBAL",2) 
Global("SarahRomanceActive","GLOBAL",2) 
Global("T#DaceRomanceActive","GLOBAL",2) 
Global("SimeRomanceActive","GLOBAL",2)
Global("rh#IsraRomanceActive","GLOBAL",2)
Global("C0SireneRomanceActive","GLOBAL",2)
Global("HexxatRomanceActive","GLOBAL",2)
Global("NeeraRomanceActive","GLOBAL",2)
THEN
RESPONSE #100
SetGlobal("L0Player1Gay","GLOBAL",1)
END

IF
Gender(Player1,MALE)
Global("L0Player1Gay","GLOBAL",0)
OR(8)
Global("AnomenRomanceActive","GLOBAL",2)
GlobalGT("SolaTalk","GLOBAL",14)
Global("FHFarenRomanceActive","GLOBAL",2) 
Global("LK#ArathRomanceActive","GLOBAL",2) 
Global("L7TsukiSexActive","GLOBAL",2)
Global("NathRomanceActive","GLOBAL",2) 
Global("DornRomanceActive","GLOBAL",2)
Global("RasaadRomanceActive","GLOBAL",2)
THEN
RESPONSE #100
SetGlobal("L0Player1Gay","GLOBAL",1)
END

IF
InParty(Myself)
Global("L0Player1RomanceCheck","GLOBAL",0)
OR(44)
Global("LS_HaerdalisRomanceActive","GLOBAL",2)
Global("C0SireneRomanceActive","GLOBAL",2)
Global("HexxatRomanceActive","GLOBAL",2)
Global("NeeraRomanceActive","GLOBAL",2)
Global("DornRomanceActive","GLOBAL",2)
Global("RasaadRomanceActive","GLOBAL",2)
Global("JaheiraRomanceActive","GLOBAL",2)
Global("ViconiaRomanceActive","GLOBAL",2)
Global("AerieRomanceActive","GLOBAL",2)
Global("AnomenRomanceActive","GLOBAL",2)
GlobalGT("SolaTalk","GLOBAL",14)
Global("NathRomanceActive","GLOBAL",2) 
Global("FHFarenRomanceActive","GLOBAL",2) 
Global("LK#ArathRomanceActive","GLOBAL",2) 
Global("L7TsukiSexActive","GLOBAL",2)
Global("ChloeRomanceActiveCR","GLOBAL",2) 
Global("SarahRomanceActive","GLOBAL",2) 
Global("T#DaceRomanceActive","GLOBAL",2) 
Global("SimeRomanceActive","GLOBAL",2)
Global("J#KelseyRomanceActive","GLOBAL",2)
Global("TsujathaRomanceActive","GLOBAL",2)
Global("SaerilethRomanceActive","GLOBAL",2)
Global("TashiaRomanceActive","GLOBAL",2)
Global("H#ValygarRomanceActive","GLOBAL",2)
Global("ImoenRomanceActive","GLOBAL",2)
Global("NaliaRomanceActive","GLOBAL",2)
Global("E3FADEROMANCEACTIVE","GLOBAL",2)
Global("O#XanRomanceActive","GLOBAL",2)
Global("M#AmberRomanceActive","GLOBAL",2)
Global("C#AjantisRomanceActive","GLOBAL",2)
Global("LK#NindeRomanceActive","GLOBAL",2)
Global("ADAngelRomanceActive","GLOBAL",2)
Global("B!GavRA","GLOBAL",2)
Global("SK#NehtRomanceActive","GLOBAL",2)
Global("G#TF.TyrisRomanceActive","GLOBAL",2)
Global("T1DarRomanceActive","GLOBAL",2)
Global("B!KeldornRA","GLOBAL",2)
Global("EdwinRomanceActive","GLOBAL",2)
Global("YvetteRomanceActive","GLOBAL",2)
Global("SkieRomanceActive","GLOBAL",2)
Global("rh#AdrianRomanceActive","GLOBAL",2)
Global("LK#ArathRomanceActive","GLOBAL",2)
Global("L3PetsyRomanceActive","GLOBAL",2)
Global("rh#IsraRomanceActive","GLOBAL",2)
THEN
RESPONSE #100
RealSetGlobalTimer("L0Player1RomanceCheckT","GLOBAL",20)
SetGlobal("L0Player1RomanceCheck","GLOBAL",1)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
RealGlobalTimerExpired("L0Player1RomanceCheckT","GLOBAL")
Global("L0Player1RomanceCheck","GLOBAL",1)
Global("L0WillDialogue","GLOBAL",20)
THEN
RESPONSE #100
SetGlobal("L0Player1RomanceCheck","GLOBAL",2)
END

IF
Global("L0Player1RomanceCheck","GLOBAL",2)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogue("L0WillJ",Player1)
END


/////////////////////////////////////

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
Global("L0WillRelationshipActive","GLOBAL",0)
Global("L0Player1RomanceCheck","GLOBAL",4)
THEN
RESPONSE #100
RealSetGlobalTimer("L0Player1RomanceCheckT","GLOBAL",1600)
SetGlobal("L0WillRelationshipActive","GLOBAL",1)
SetGlobal("L0Player1RomanceCheck","GLOBAL",5)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
Global("L0WillRelationshipActive","GLOBAL",1)
RealGlobalTimerExpired("L0Player1RomanceCheckT","GLOBAL")
Global("L0Player1RomanceCheck","GLOBAL",5)
THEN
RESPONSE #100
SetGlobal("L0Player1RomanceCheck","GLOBAL",6)
END

IF
Global("L0Player1RomanceCheck","GLOBAL",6)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogue("L0WillJ",Player1)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
Global("L0WillRelationshipActive","GLOBAL",1)
Global("L0Player1RomanceCheck","GLOBAL",7)
THEN
RESPONSE #100
RealSetGlobalTimer("L0Player1RomanceCheckT","GLOBAL",1600)
SetGlobal("L0Player1RomanceCheck","GLOBAL",8)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
Global("L0WillRelationshipActive","GLOBAL",1)
RealGlobalTimerExpired("L0Player1RomanceCheckT","GLOBAL")
Global("L0Player1RomanceCheck","GLOBAL",8)
THEN
RESPONSE #100
SetGlobal("L0Player1RomanceCheck","GLOBAL",9)
END

IF
Global("L0Player1RomanceCheck","GLOBAL",9)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogue("L0WillJ",Player1)
END


IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
Global("L0WillRelationshipActive","GLOBAL",2)
Global("L0Player1RomanceCheck","GLOBAL",10)
THEN
RESPONSE #100
RealSetGlobalTimer("L0Player1RomanceCheckT","GLOBAL",1600)
SetGlobal("L0Player1RomanceCheck","GLOBAL",11)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
Global("L0WillRelationshipActive","GLOBAL",2)
RealGlobalTimerExpired("L0Player1RomanceCheckT","GLOBAL")
Global("L0Player1RomanceCheck","GLOBAL",11)
THEN
RESPONSE #100
SetGlobal("L0Player1RomanceCheck","GLOBAL",12)
END

IF
Global("L0Player1RomanceCheck","GLOBAL",12)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogue("L0WillJ",Player1)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
Global("L0WillRelationshipActive","GLOBAL",2)
Global("L0Player1RomanceCheck","GLOBAL",13)
THEN
RESPONSE #100
RealSetGlobalTimer("L0Player1RomanceCheckT","GLOBAL",1600)
SetGlobal("L0Player1RomanceCheck","GLOBAL",14)
END

IF
Global("L0Player1RomanceCheck","GLOBAL",15)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogue("L0WillJ",Player1)
END


IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
Global("L0WillRelationshipActive","GLOBAL",3)
Global("L0WillCharnameNoLove","GLOBAL",1)
THEN
RESPONSE #100
RealSetGlobalTimer("L0Player1StrangeTalk","GLOBAL",6000)
SetGlobal("L0WillCharnameNoLove","GLOBAL",2)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
RealGlobalTimerExpired("L0Player1StrangeTalk","GLOBAL")
Global("L0WillRelationshipActive","GLOBAL",3)
Global("L0WillCharnameNoLove","GLOBAL",2)
THEN
RESPONSE #100
SetGlobal("L0WillCharnameNoLove","GLOBAL",3)
END

IF
Global("L0WillCharnameNoLove","GLOBAL",3)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogue("L0WillJ",Player1)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
Global("L0WillRelationshipActive","GLOBAL",3)
Global("L0WillCharnameNoLove","GLOBAL",4)
THEN
RESPONSE #100
RealSetGlobalTimer("L0Player1StrangeTalk","GLOBAL",12000)
SetGlobal("L0WillCharnameNoLove","GLOBAL",5)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
RealGlobalTimerExpired("L0Player1StrangeTalk","GLOBAL")
Global("L0WillRelationshipActive","GLOBAL",3)
Global("L0WillCharnameNoLove","GLOBAL",5)
THEN
RESPONSE #100
SetGlobal("L0WillCharnameNoLove","GLOBAL",6)
END

IF
Global("L0WillCharnameNoLove","GLOBAL",6)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogue("L0WillJ",Player1)
END


/////////////////// Drunk Talk

IF
InParty(Myself)
Global("L0WillRelationshipActive","GLOBAL",2)
Global("L0WillDrunkTalk","GLOBAL",0)
CheckStatGT(Player1,50,INTOXICATION)
OR(11)
AreaCheck("AR0509")
AreaCheck("AR0021")
AreaCheck("AR0406")
AreaCheck("AR0313")
AreaCheck("AR0704")
AreaCheck("AR0709")
AreaCheck("AR0513")
AreaCheck("AR1602")
AreaCheck("AR1105")
AreaCheck("AR2010")
AreaCheck("AR2202")
See(Player1)
CombatCounter(0)
!See([ENEMY])
THEN
RESPONSE #100
SetGlobal("L0WillDrunkTalk","GLOBAL",1)
END

IF
Global("L0WillDrunkTalk","GLOBAL",1)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogue("L0WillJ",Player1)
END

/////////////////// Reputation Talk

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
ReputationGT(Player1,18)
Global("L0WillRepTalk","GLOBAL",0)
THEN
RESPONSE #100
RealSetGlobalTimer("L0Player1RepTalk","GLOBAL",60)
SetGlobal("L0WillRepTalk","GLOBAL",1)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
See(Player1)
RealGlobalTimerExpired("L0Player1RepTalk","GLOBAL")
Global("L0WillRepTalk","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("L0WillRepTalk","GLOBAL",2)
END

IF
Global("L0WillRepTalk","GLOBAL",2)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogue("L0WillJ",Player1)
END

//////////////////////////////////
//////////QUEST///////////////////
//////////////////////////////////

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
AreaCheck("AR2100")
See("Hidden1")
Global("L0WillQuestUD","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("L0WillQuestUD","GLOBAL",1)
END

IF
Global("L0WillQuestUD","GLOBAL",1)
THEN
RESPONSE #100
StartDialogue("L0WillJ",Player1)
END

IF
Global("L0WillQuestUD","GLOBAL",2)
THEN
RESPONSE #100
StartCutScene("L0CUT04")
END

IF
Global("L0WillQuestUD","GLOBAL",3)
THEN
RESPONSE #100
StartDialogue("L0WillJ",Player1)
END

IF
InParty(Myself)
CombatCounter(0)
Dead("L0UDBEA")
OR(2)
Global("L0WillQuestUD","GLOBAL",4)
Global("L0WillQuestUD","GLOBAL",5)
THEN
RESPONSE #100
SetGlobal("L0WillQuestUD","GLOBAL",6)
END

IF
Global("L0WillQuestUD","GLOBAL",6)
THEN
RESPONSE #100
StartDialogue("L0WillJ",Player1)
END

IF
InParty(Myself)
CombatCounter(0)
!See([ENEMY])
AreaCheck("AR2100")
Global("L0WillQuestUD","GLOBAL",7)
THEN
RESPONSE #100
SetGlobal("L0WillQuestUD","GLOBAL",8)
END

IF
Global("L0WillQuestUD","GLOBAL",8)
THEN
RESPONSE #100
StartDialogue("L0WillJ",Player1)
END