IF
RandomNum(5,1)
See(NearestEnemyOf(Myself))
Global("L0AttackWithSpells","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("L0AttackWithSpells","LOCALS",1)
ForceSpell(NearestEnemyOf(Myself),WIZARD_BLINDNESS)
END

IF
RandomNum(5,2)
See(NearestEnemyOf(Myself))
Global("L0AttackWithSpells","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("L0AttackWithSpells","LOCALS",1)
ForceSpell(NearestEnemyOf(Myself),WIZARD_LARLOCH_MINOR_DRAIN)
END

IF
RandomNum(5,3)
See(NearestEnemyOf(Myself))
Global("L0AttackWithSpells","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("L0AttackWithSpells","LOCALS",1)
ForceSpell(Myself,WIZARD_REFLECTED_IMAGE)
END

IF
RandomNum(5,4)
See(NearestEnemyOf(Myself))
Global("L0AttackWithSpells","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("L0AttackWithSpells","LOCALS",1)
ForceSpell(NearestEnemyOf(Myself),WIZARD_LIGHTNING_BOLT)
END

IF
RandomNum(5,5)
See(NearestEnemyOf(Myself))
Global("L0AttackWithSpells","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("L0AttackWithSpells","LOCALS",1)
ForceSpell(NearestEnemyOf(Myself),WIZARD_EMOTION_HOPELESSNESS)
END

IF
Global("L0AttackWithSpells","LOCALS",1)
See(NearestEnemyOf(Myself))
THEN
RESPONSE #100
AttackReevaluate(NearestEnemyOf(Myself),10)
END