IF
Range(NearestEnemyOf(Myself),10)
Global("L0AttackWithColors","LOCALS",0)
THEN
RESPONSE #100
ForceSpell([PC],WIZARD_COLOR_SPRAY)
SetGlobal("L0AttackWithColors","LOCALS",1)
END

IF
See(NearestEnemyOf(Myself))
Global("L0AttackWithColors","LOCALS",0)
!Range(NearestEnemyOf(Myself),10)
THEN
RESPONSE #100
MoveToObject(NearestEnemyOf())
END

IF
Global("L0AttackWithColors","LOCALS",1)
See(NearestEnemyOf(Myself))
THEN
RESPONSE #100
AttackReevaluate(NearestEnemyOf(Myself),10)
END